In [53]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
#from google.colab import drive
import warnings
warnings.filterwarnings('ignore')

In [54]:
#drive.mount('/content/drive') # Uncomment if loading from Google Drive
#cancer_df = pd.read_csv('/content/drive/My Drive/PROYECTOS/DM_II_project/data/raw/patient_train_data.csv') # Uncomment if loading from Google Drive .Load the data from Google Drive
cancer_df = pd.read_csv('g:/Mi unidad/PROYECTOS/DM_II_project/data/raw/patient_train_data.csv') # Uncomment if loading from local directory

In [55]:
cancer_df.head()

,ID,Alcohol Consumption,Cancer Stage,Country,Date of Birth,Diabetes,Diabetes History,Diet Risk,Early Detection,Family History,...,Non Smoker,Obesity BMI,Physical Activity,Screening History,Smoking History,Transfusion History,Treatment Type,Tumor Size (mm),Urban or Rural,Survival Prediction
0,1,No,Localized,UK,29-01-1966,No,No,Moderate,No,No,...,Yes,Overweight,Low,Regular,No,-,Chemotherapy,33.0,Urban,Yes
1,2,No,Regional,Japan,21-12-1958,No,No,Low,No,No,...,No,Normal,Low,Irregular,Yes,-,Chemotherapy,17.0,Urban,No
2,3,No,Localized,France,16-06-1959,No,No,Low,Yes,No,...,No,Normal,Moderate,Never,Yes,-,Surgery,34.0,Urban,Yes
3,4,Yes,Localized,Japan,18-01-1956,Yes,No,Moderate,No,No,...,Yes,Obese,Low,Regular,No,-,Radiotherapy,71.0,Urban,No
4,5,No,Regional,USA,04-05-1975,No,No,Moderate,Yes,Yes,...,Yes,Overweight,Low,Regular,No,-,Radiotherapy,48.0,Rural,Yes

# 1. Basic cleaning and data split

Three columns were dropped from the `cancer_df` dataframe: 'Diabetes History', 'Marital Status', and 'Transfusion History'.

In [56]:
cancer_df_reduced = cancer_df.drop(columns=['Diabetes History', 'Marital Status', 'Transfusion History'], axis=1).copy()

The country names in the `cancer_df_reduced` dataframe were replaced by their respective continents to reduce the cardinality of the categorical variable. This helps in simplifying the analysis and modeling by grouping countries into broader regions.

In [57]:
cancer_df_reduced['Country'].unique()

array(['UK', 'Japan', 'France', 'USA', 'China', 'South Korea', 'Brazil',
       'Germany', 'Canada', 'Pakistan', 'Italy', 'New Zealand',
       'South Africa', 'India', 'Nigeria', 'Australia', nan], dtype=object)

In [58]:
continents = {
    'USA': 'North America',
    'Brazil': 'South America',
    'Germany': 'Europe',
    'France': 'Europe',
    'Italy': 'Europe',
    'UK': 'Europe',
    'China': 'Asia',
    'Japan': 'Asia',
    'India': 'Asia',
    'South Korea': 'Asia',
    'Pakistan': 'Asia',
    'South Africa': 'Africa',
    'Nigeria': 'Africa',
    'Australia': 'Oceania',
    'New Zealand': 'Oceania'
}
cancer_df_reduced['Continent'] = cancer_df_reduced['Country'].replace(continents)
cancer_df_reduced.drop(columns=['Country'], inplace=True)
cancer_df_reduced['Continent'].head()

0           Europe
1             Asia
2           Europe
3             Asia
4    North America
Name: Continent, dtype: object

The birth dates in the dataframe were converted to datetime format, and the age of each patient was calculated based on the current year. The original birth date column was then removed from the dataframe.

In [59]:
from datetime import datetime

cancer_df_reduced['Date of Birth'] = pd.to_datetime(cancer_df_reduced['Date of Birth'], format='%d-%m-%Y', errors='coerce')
cancer_df_reduced['Age'] = cancer_df_reduced['Date of Birth'].apply(lambda x: datetime.now().year - x.year if pd.notnull(x) else None)
cancer_df_reduced.drop(columns=['Date of Birth'], inplace=True)
cancer_df_reduced['Age'].head()

0    59.0
1    67.0
2    66.0
3    69.0
4    50.0
Name: Age, dtype: float64

The 'Urban or Rural' column values were standardized by replacing 'urban' with 'Urban' and 'rural' with 'Rural' to ensure consistency in the dataset.

In [60]:
cancer_df_reduced['Urban or Rural'].unique()

array(['Urban', 'Rural', 'urban', 'rural', nan], dtype=object)

In [61]:
cancer_df_reduced['Urban or Rural'].replace({'urban': 'Urban', 'rural': 'Rural'}, inplace=True)
cancer_df_reduced['Urban or Rural'].unique()

array(['Urban', 'Rural', nan], dtype=object)

Column 'ID' is removed as it will not be used for training the model.

In [62]:
cancer_df_reduced.drop(columns=['ID'], axis=1, inplace=True)

In [63]:
cancer_df_reduced.head()

,Alcohol Consumption,Cancer Stage,Diabetes,Diet Risk,Early Detection,Family History,Gender,Genetic Mutation,Healthcare Access,Healthcare Costs,...,Obesity BMI,Physical Activity,Screening History,Smoking History,Treatment Type,Tumor Size (mm),Urban or Rural,Survival Prediction,Continent,Age
0,No,Localized,No,Moderate,No,No,M,No,High,76553.0,...,Overweight,Low,Regular,No,Chemotherapy,33.0,Urban,Yes,Europe,59.0
1,No,Regional,No,Low,No,No,M,No,Moderate,62805.0,...,Normal,Low,Irregular,Yes,Chemotherapy,17.0,Urban,No,Asia,67.0
2,No,Localized,No,Low,Yes,No,M,No,High,66425.0,...,Normal,Moderate,Never,Yes,Surgery,34.0,Urban,Yes,Europe,66.0
3,Yes,Localized,Yes,Moderate,No,No,M,No,Moderate,82764.0,...,Obese,Low,Regular,No,Radiotherapy,71.0,Urban,No,Asia,69.0
4,No,Regional,No,Moderate,Yes,Yes,M,No,Low,47269.0,...,Overweight,Low,Regular,No,Radiotherapy,48.0,Rural,Yes,North America,50.0

The dataset was split into training, validation, and test sets to ensure robust model evaluation and to prevent overfitting. The initial split separated 15% of the data as the test set, which will be used for the final evaluation of the model's performance. This ensures that the test set remains completely unseen during the training and validation phases, providing an unbiased assessment of the model's generalization capability.

The proportions were chosen to maintain a balance between having enough data for training the model and having sufficient data for validation and testing to ensure reliable performance metrics.

In [64]:
test_count = cancer_df_reduced['Survival Prediction']
test_count.value_counts()

Survival Prediction
Yes    45069
No     29966
Name: count, dtype: int64

In [65]:
cancer_df_reduced['Survival Prediction'].replace({'Yes': 1, 'No': 0}, inplace=True)

In [66]:
from sklearn.model_selection import train_test_split

X = cancer_df_reduced.drop(columns=['Survival Prediction'])
y = cancer_df_reduced['Survival Prediction']

# First split to separate the test set (15% of the data)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42, stratify=y)

# Split the remaining data into training and validation sets
# test_size=0.1765 because 15/85 ≈ 0.1765 (to get 15% of the original total)
#X_train, X_val, y_train, y_val = train_test_split(X_temp, y_temp, test_size=0.1765, random_state=42, stratify=y_temp)


print(f"X_train shape: {X_train.shape}")
#print(f"X_val shape: {X_val.shape}")
print(f"X_test shape: {X_test.shape}")


print(f"y_train shape: {y_train.shape}")
#print(f"X_val shape: {y_val.shape}")
print(f"y_test shape: {y_test.shape}")

X_train shape: (60028, 27)
X_test shape: (15007, 27)
y_train shape: (60028,)
y_test shape: (15007,)

# 3. PREPROCESSING PIPELINE

In [79]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import FunctionTransformer, RobustScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn.feature_selection import SelectKBest, f_classif
from scipy import stats
import numpy as np

Winsorization of numeric columns with outliers

In [80]:
def winsorize_columns(X):
    for column_index in range(X.shape[1]):  # Iterar sobre índices de columnas
        Q1 = np.percentile(X[:, column_index], 25)
        Q3 = np.percentile(X[:, column_index], 75)
        IQR = Q3 - Q1
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR
        X[:, column_index] = np.clip(X[:, column_index], lower_bound, upper_bound)
    return X

In [81]:
def negative_imputer(X):
    for column_index in range(X.shape[1]):
        median_c = np.median(X[:, column_index])
        X[:, column_index] = np.where(X[:, column_index] < 0, X[:, column_index]*-1, X[:, column_index])
    return X

In [82]:
numerical_columns = X_train.select_dtypes(include='number').columns
categorical_columns= X_train.select_dtypes(exclude='number').columns.to_list()

steps_numerical = []
steps_numerical.append(('imputer', SimpleImputer(strategy='median')))
steps_numerical.append(('negative imputer', FunctionTransformer(negative_imputer)))
steps_numerical.append(('winsorizer', FunctionTransformer(winsorize_columns)))
steps_numerical.append(('scaler', RobustScaler()))

numerical_transformer = Pipeline(steps=steps_numerical)

steps_categorical = []
steps_categorical.append(('imputer', SimpleImputer(strategy='most_frequent')))
steps_categorical.append(('encoder', OneHotEncoder(handle_unknown='ignore')))

categorical_transformer = Pipeline(steps=steps_categorical)

preprocessor = ColumnTransformer(transformers=[('num', numerical_transformer, numerical_columns), ('cat', categorical_transformer, categorical_columns)])

In [1]:
#Helo World

# 4. HOLDOUT

## Dummy Classifier

In [ ]:
from sklearn.dummy import DummyClassifier
from sklearn.metrics import classification_report

# Crear un modelo ZeroR
zero_r = DummyClassifier(strategy="most_frequent")

# Entrenar el modelo
pipeline_zeror = Pipeline(steps=[('preprocessor', preprocessor), ('classifier', zero_r)])
pipeline_zeror.fit(X_train, y_train)

# Hacer predicciones
y_pred_zeror = zero_r.predict(X_test)

# Evaluar el modelo
print("ZeroR Classification Report:")
print(classification_report(y_test, y_pred_zeror))

ZeroR Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00      2997
           1       0.60      1.00      0.75      4507

    accuracy                           0.60      7504
   macro avg       0.30      0.50      0.38      7504
weighted avg       0.36      0.60      0.45      7504

c:\Users\Gabriel\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Gabriel\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Gabriel\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

## Random Forest

In [ ]:
from imblearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from imblearn.combine import SMOTEENN
from imblearn.pipeline import Pipeline


random_forest = RandomForestClassifier(
    n_estimators=100,
    max_depth=10,
    min_samples_split=10,
    min_samples_leaf=5,
    max_features='sqrt',
    bootstrap=True,
    class_weight='balanced',
    random_state=42
)

pipeline = Pipeline(steps=[('preprocessor', preprocessor), ('resampler', SMOTEENN(random_state=42)),('model', random_forest)])
pipeline.fit(X_train, y_train)

y_pred_rf = pipeline.predict(X_test)
y_pred_rf_train = pipeline.predict(X_train)

print("Classification (test) Report:")
print(classification_report(y_test, y_pred_rf))

print("Classification (training) Report:")
print(classification_report(y_train, y_pred_rf_train))

Classification (test) Report:
              precision    recall  f1-score   support

           0       0.39      0.24      0.29      2997
           1       0.60      0.75      0.67      4507

    accuracy                           0.55      7504
   macro avg       0.49      0.50      0.48      7504
weighted avg       0.51      0.55      0.52      7504

Classification (training) Report:
              precision    recall  f1-score   support

           0       0.47      0.30      0.37     26969
           1       0.63      0.77      0.69     40562

    accuracy                           0.58     67531
   macro avg       0.55      0.54      0.53     67531
weighted avg       0.56      0.58      0.56     67531

In [ ]:
from sklearn.ensemble import RandomForestClassifier


random_forest = RandomForestClassifier(
    n_estimators=100,
    max_depth=10,
    min_samples_split=10,
    min_samples_leaf=5,
    max_features='sqrt',
    bootstrap=True,
    class_weight='balanced',
    random_state=42
)

pipeline = Pipeline(steps=[('preprocessor', preprocessor),('model', random_forest)])
pipeline.fit(X_train, y_train)

y_pred_rf = pipeline.predict(X_test)
y_pred_rf_train = pipeline.predict(X_train)

print("Classification (test) Report:")
print(classification_report(y_test, y_pred_rf))

print("Classification (training) Report:")
print(classification_report(y_train, y_pred_rf_train))

Classification (test) Report:
              precision    recall  f1-score   support

           0       0.41      0.40      0.40      2997
           1       0.60      0.61      0.61      4507

    accuracy                           0.53      7504
   macro avg       0.51      0.51      0.51      7504
weighted avg       0.53      0.53      0.53      7504

Classification (training) Report:
              precision    recall  f1-score   support

           0       0.71      0.76      0.74     26969
           1       0.83      0.79      0.81     40562

    accuracy                           0.78     67531
   macro avg       0.77      0.78      0.78     67531
weighted avg       0.79      0.78      0.78     67531

## Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression

logistic_model = LogisticRegression(class_weight='balanced', max_iter=100000, random_state=42)

pipeline_logistic = Pipeline(steps=[('preprocessor', preprocessor), ('model', logistic_model)])
pipeline_logistic.fit(X_train, y_train)

y_pred_logistic = pipeline_logistic.predict(X_test)
y_pred_logistic_train = pipeline_logistic.predict(X_train)

print("Classification (test) Report:")
print(classification_report(y_test, y_pred_logistic))

print("Classification (training) Report:")
print(classification_report(y_train, y_pred_logistic_train))

Classification (test) Report:
              precision    recall  f1-score   support

           0       0.40      0.50      0.45      2997
           1       0.61      0.51      0.55      4507

    accuracy                           0.51      7504
   macro avg       0.50      0.50      0.50      7504
weighted avg       0.52      0.51      0.51      7504

Classification (training) Report:
              precision    recall  f1-score   support

           0       0.41      0.51      0.45     26969
           1       0.61      0.51      0.55     40562

    accuracy                           0.51     67531
   macro avg       0.51      0.51      0.50     67531
weighted avg       0.53      0.51      0.51     67531

## KNN

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
param_grid = {
    'model__n_neighbors': [3, 5, 7, 9],
    'model__weights': ['uniform', 'distance'],
    'model__metric': ['euclidean', 'manhattan']
}

pipeline_knn_gv = Pipeline(steps=[('preprocessor', preprocessor),
                               ('model', KNeighborsClassifier())])
grid_search = GridSearchCV(pipeline_knn_gv, param_grid, cv=5, scoring='f1_weighted')
grid_search.fit(X_train, y_train)
print("Best Parameters:", grid_search.best_params_)

Best Parameters: {'model__metric': 'euclidean', 'model__n_neighbors': 9, 'model__weights': 'distance'}

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline

knn_model = KNeighborsClassifier(weights='distance', metric = 'euclidean', n_neighbors=9)

pipeline_knn = Pipeline(steps=[('preprocessor', preprocessor), ('smote', SMOTE(random_state=42)),('model', logistic_model)])
pipeline_knn.fit(X_train, y_train)

y_pred_knn = pipeline_knn.predict(X_test)
y_pred_knn_train = pipeline_knn.predict(X_train)

print("Classification (test) Report:")
print(classification_report(y_test, y_pred_knn))

print("XGBoost Classification (training) Report:")
print(classification_report(y_train, y_pred_knn_train))

Classification (test) Report:
              precision    recall  f1-score   support

           0       0.40      0.52      0.45      2997
           1       0.60      0.48      0.53      4507

    accuracy                           0.49      7504
   macro avg       0.50      0.50      0.49      7504
weighted avg       0.52      0.49      0.50      7504

XGBoost Classification (training) Report:
              precision    recall  f1-score   support

           0       0.40      0.54      0.46     26969
           1       0.61      0.48      0.53     40562

    accuracy                           0.50     67531
   macro avg       0.51      0.51      0.50     67531
weighted avg       0.53      0.50      0.50     67531

## NAIVE BAYES

In [ ]:
from sklearn.naive_bayes import GaussianNB, MultinomialNB
from sklearn.compose import ColumnTransformer

# Dividir las columnas en continuas y categóricas
numerical_columns = X_train.select_dtypes(include=['number']).columns
categorical_columns = X_train.select_dtypes(exclude=['number']).columns

X_train_num = X_train[numerical_columns]
X_train_cat = X_train[categorical_columns]
X_test_num = X_test[numerical_columns]
X_test_cat = X_test[categorical_columns]


# Entrenar Gaussian Naive Bayes para variables continuas
gaussian_nb = GaussianNB()
pipeline_gnb = Pipeline(steps=[('preprocessor', numerical_transformer), ('model', gaussian_nb)])
pipeline_gnb.fit(X_train_num, y_train)

# Entrenar Multinomial Naive Bayes para variables categóricas
multinomial_nb = MultinomialNB()
pipeline_mnb = Pipeline(steps=[('preprocessor', categorical_transformer), ('model', multinomial_nb)])
pipeline_mnb.fit(X_train_cat, y_train)

# Obtener probabilidades de predicción de ambos modelos
gaussian_probs = pipeline_gnb.predict_proba(X_test_num)
multinomial_probs = pipeline_mnb.predict_proba(X_test_cat)

#gaussian_probs_train = pipeline_gnb.predict_proba(X_train_num)
#multinomial_probs_train = pipeline_mnb.predict_proba(X_train_cat)

# Combinar probabilidades (puedes ajustar los pesos según sea necesario)
combined_probs = (gaussian_probs + multinomial_probs) / 2
#combined_probs_train = (gaussian_probs_train + multinomial_probs_train) / 2

# Predicción final basada en las probabilidades combinadas
threshold = 0.6
y_pred_nb = (combined_probs[:, 1] >= threshold).astype(int)
#y_pred_nb_train = (combined_probs_train[:, 1] >= threshold).astype(int)


# Evaluate the model
print("XGBoost Classification Report (test):")
print(classification_report(y_test, y_pred_nb))

print("XGBoost Classification Report (training):")
#print(classification_report(y_train, y_pred_nb_train))

TypeError: All intermediate steps of the chain should not be Pipelines

## XGBOOST

### Random Search

In [ ]:
from sklearn.model_selection import RandomizedSearchCV
from xgboost import XGBClassifier
import numpy as np


xgb_model = XGBClassifier(random_state=42)


param_dist = {
    'learning_rate': np.linspace(0.01, 0.3, 10),
    'max_depth': [3, 5, 7, 9],
    'n_estimators': [50, 100, 200, 300],
    'subsample': [0.6, 0.8, 1.0],
    'colsample_bytree': [0.6, 0.8, 1.0],
    'scale_pos_weight': [1, len(y_train[y_train == 0]) / len(y_train[y_train == 1])]
}


random_search = RandomizedSearchCV(
    estimator=xgb_model,
    param_distributions=param_dist,
    n_iter=50,
    scoring='f1_weighted',
    cv=5,
    n_jobs=-1,
    random_state=42,
    verbose=1
)


pipeline_randomsearch = Pipeline(steps=[
    ('preprocessor', preprocessor),
      ('smote', SMOTE(random_state=42)),  # Preprocesamiento
    ('model', random_search)
])

# Entrenar el modelo
pipeline_randomsearch.fit(X_train, y_train)

# Imprimir los mejores parámetros
print("Best Parameters:", random_search.best_params_)
print("Best F1-Weighted Score:", random_search.best_score_)

KeyboardInterrupt:

### Running with best parameters

In [ ]:
from xgboost import XGBClassifier
from sklearn.metrics import classification_report
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline

xgb_model = XGBClassifier(
    scale_pos_weight=1,
    random_state=42,
    learning_rate=0.3,
    max_depth=9,
    n_estimators=300,
    subsample=0.6,
    colsample_bytree=0.8
)

pipeline_xgb = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('smote', SMOTE(random_state=42)),
    ('model', xgb_model)
])

pipeline_xgb.fit(X_train, y_train)

y_pred_xgb = pipeline_xgb.predict(X_test)

y_pred_xgb_train = pipeline_xgb.predict(X_train)

print("XGBoost Classification (test) Report:")
print(classification_report(y_test, y_pred_xgb))

print("XGBoost Classification (training) Report:")
print(classification_report(y_train, y_pred_xgb_train))

XGBoost Classification (test) Report:
              precision    recall  f1-score   support

           0       0.39      0.31      0.35      2997
           1       0.60      0.68      0.64      4507

    accuracy                           0.53      7504
   macro avg       0.50      0.50      0.49      7504
weighted avg       0.52      0.53      0.52      7504

XGBoost Classification (training) Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     26969
           1       1.00      1.00      1.00     40562

    accuracy                           1.00     67531
   macro avg       1.00      1.00      1.00     67531
weighted avg       1.00      1.00      1.00     67531

In [ ]:
from xgboost import XGBClassifier
from sklearn.metrics import classification_report
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline

scale_pos_weight = len(y_train[y_train == 0]) / len(y_train[y_train == 1])

xgb_model = XGBClassifier(
    scale_pos_weight=scale_pos_weight,
    random_state=42,
    learning_rate=0.1,
    max_depth=3,
    n_estimators=400,
    subsample=0.8,
    colsample_bytree=0.8,
    gamma=0.5,
    reg_lambda=1,
    reg_alpha=0.1,
)

pipeline_xgb = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('smote', SMOTE(random_state=42)),
    ('model', xgb_model)
])

pipeline_xgb.fit(X_train, y_train)

y_pred_xgb = pipeline_xgb.predict(X_test)

y_pred_xgb_train = pipeline_xgb.predict(X_train)

print("XGBoost Classification (test) Report:")
print(classification_report(y_test, y_pred_xgb))

print("XGBoost Classification (training) Report:")
print(classification_report(y_train, y_pred_xgb_train))

XGBoost Classification (test) Report:
              precision    recall  f1-score   support

           0       0.40      0.56      0.47      2997
           1       0.61      0.45      0.52      4507

    accuracy                           0.50      7504
   macro avg       0.51      0.51      0.49      7504
weighted avg       0.53      0.50      0.50      7504

XGBoost Classification (training) Report:
              precision    recall  f1-score   support

           0       0.46      0.64      0.53     26969
           1       0.68      0.50      0.57     40562

    accuracy                           0.56     67531
   macro avg       0.57      0.57      0.55     67531
weighted avg       0.59      0.56      0.56     67531

## NEURAL NETWORKS

In [ ]:
from sklearn.neural_network import MLPClassifier
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline

mlp_model = MLPClassifier(hidden_layer_sizes=(100, 50), max_iter=1000, random_state=42, activation='tanh')
pipeline_mlp = Pipeline(steps=[('preprocessor', preprocessor), ('smote', SMOTE(random_state=42)), ('model', mlp_model)])
pipeline_mlp.fit(X_train, y_train)
y_pred_mlp = pipeline_mlp.predict(X_test)
print(classification_report(y_test, y_pred_mlp))

              precision    recall  f1-score   support

           0       0.39      0.42      0.41      2997
           1       0.60      0.57      0.58      4507

    accuracy                           0.51      7504
   macro avg       0.50      0.50      0.50      7504
weighted avg       0.52      0.51      0.51      7504

# 5. CROSS VALIDATION

In [ ]:
#from sklearn.model_selection import cross_val_score

#scores = cross_val_score(pipeline_logistic, X_train, y_train, cv=10)
#print("Cross-validation scores:", scores)

In [ ]:
from sklearn.linear_model import LogisticRegression
#from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from xgboost import XGBClassifier
#from sklearn.svm import SVC
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier

models = []
#models.append(('LR', LogisticRegression(solver='liblinear', multi_class='ovr')))
#models.append(('LDA', LinearDiscriminantAnalysis()))
models.append(('LR', LogisticRegression(max_iter=1000, random_state=42)))
models.append(('KNN', KNeighborsClassifier()))
models.append(('DT', DecisionTreeClassifier(random_state=42)))
models.append(('RF', RandomForestClassifier(random_state=42)))
models.append(('NB', GaussianNB()))
#models.append(('XGBoost', XGBClassifier(use_label_encoder=False, eval_metric='logloss', random_state=42)))
#models.append(('SVM', SVC(gamma='auto')))
# evaluate each model in turn
results = []
names = []
for name, model in models:
    pipeline_model = Pipeline(steps=[('preprocessor', preprocessor), ('model', model)])
    kfold = StratifiedKFold(n_splits=10, random_state=1, shuffle=True)
    cv_results = cross_val_score(pipeline_model, X_train, y_train, cv=kfold, scoring='accuracy')
    results.append(cv_results)
    names.append(name)
    print('%s: %f (%f)' % (name, cv_results.mean(), cv_results.std()))

LR: 0.600643 (0.000046)
KNN: 0.534969 (0.006548)
DT: 0.516607 (0.005811)
RF: 0.586264 (0.003350)
NB: 0.590914 (0.027205)

ValueError:
All the 10 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\Gabriel\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\Gabriel\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Gabriel\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\pipeline.py", line 473, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "c:\Users\Gabriel\AppData\Local\Programs\Python\Python312\Lib\site-packages\xgboost\core.py", line 729, in inner_f
    return func(**kwargs)
           ^^^^^^^^^^^^^^
  File "c:\Users\Gabriel\AppData\Local\Programs\Python\Python312\Lib\site-packages\xgboost\sklearn.py", line 1640, in fit
    raise ValueError(
ValueError: Invalid classes inferred from unique values of `y`.  Expected: [0 1], got ['No' 'Yes']

# 6. OPTUNA

In [ ]:
#!pip install optuna

Collecting optuna

WARNING: Ignoring invalid distribution ~ip (C:\Users\Gabriel\AppData\Local\Programs\Python\Python312\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Users\Gabriel\AppData\Local\Programs\Python\Python312\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Users\Gabriel\AppData\Local\Programs\Python\Python312\Lib\site-packages)

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

  Downloading optuna-4.3.0-py3-none-any.whl.metadata (17 kB)
Collecting alembic>=1.5.0 (from optuna)
  Downloading alembic-1.15.2-py3-none-any.whl.metadata (7.3 kB)
Collecting colorlog (from optuna)
  Downloading colorlog-6.9.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: numpy in c:\users\gabriel\appdata\local\programs\python\python312\lib\site-packages (from optuna) (2.1.3)
Requirement already satisfied: packaging>=20.0 in c:\users\gabriel\appdata\roaming\python\python312\site-packages (from optuna) (24.1)
Collecting sqlalchemy>=1.4.2 (from optuna)
  Downloading sqlalchemy-2.0.40-cp312-cp312-win_amd64.whl.metadata (9.9 kB)
Requirement already satisfied: tqdm in c:\users\gabriel\appdata\local\programs\python\python312\lib\site-packages (from optuna) (4.66.5)
Requirement already satisfied: PyYAML in c:\users\gabriel\appdata\local\programs\python\python312\lib\site-packages (from optuna) (6.0.2)
Collecting Mako (from alembic>=1.5.0->optuna)
  Downloading mako-1.3.10-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: typing-extensions>=4.12 in c:\users\gabriel\appdata\local\programs\python\python312\lib\site-packages (from alembic>=1.5.0->optuna) (4.12.2)
Collecting greenlet>=1 (from sqlalchemy>=1.4.2->optuna)
  Downloading greenlet-3.2.0-cp312-cp312-win_amd64.whl.metadata (4.2 kB)
Requirement already satisfied: colorama in c:\users\gabriel\appdata\roaming\python\python312\site-packages (from colorlog->optuna) (0.4.6)
Requirement already satisfied: MarkupSafe>=0.9.2 in c:\users\gabriel\appdata\local\programs\python\python312\lib\site-packages (from Mako->alembic>=1.5.0->optuna) (2.1.5)
Downloading optuna-4.3.0-py3-none-any.whl (386 kB)
Downloading alembic-1.15.2-py3-none-any.whl (231 kB)
Downloading sqlalchemy-2.0.40-cp312-cp312-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ------------------------ --------------- 1.3/2.1 MB 6.7 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 5.4 MB/s eta 0:00:00
Downloading colorlog-6.9.0-py3-none-any.whl (11 kB)
Downloading greenlet-3.2.0-cp312-cp312-win_amd64.whl (296 kB)
Downloading mako-1.3.10-py3-none-any.whl (78 kB)
Installing collected packages: Mako, greenlet, colorlog, sqlalchemy, alembic, optuna
Successfully installed Mako-1.3.10 alembic-1.15.2 colorlog-6.9.0 greenlet-3.2.0 optuna-4.3.0 sqlalchemy-2.0.40

In [87]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score
from sklearn.neighbors import KNeighborsClassifier
from xgboost import XGBClassifier
from sklearn.neural_network import MLPClassifier
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline
from sklearn.model_selection import StratifiedKFold
import optuna

## OPTIMIZING HYPERPARAMETERS

### Logistic Regression

In [47]:
def objective_logistic(trial):
    # Hiperparámetros a optimizar
    C = trial.suggest_float("C", 1e-10, 1e10, log=True)
    penalty = trial.suggest_categorical("penalty", ["l1", "l2"])
    solver = trial.suggest_categorical("solver", ["liblinear", "saga"])

    # Crear el modelo de regresión logística
    logistic_model = LogisticRegression(C=C, penalty=penalty, solver=solver, max_iter=100000, random_state=42)

    # Crear el pipeline con preprocesador y SMOTE
    pipeline = Pipeline(steps=[
        ('preprocessor', preprocessor),  # Preprocesamiento
        ('smote', SMOTE(random_state=42)),  # Balanceo de clases
        ('model', logistic_model)  # Modelo
    ])

    # Validación cruzada estratificada
    kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    
    # Evaluar el pipeline con validación cruzada
    scores = cross_val_score(pipeline, X_train, y_train, cv=kfold, scoring='f1_weighted')

    # Retornar el promedio de los F1-scores
    return scores.mean()

In [48]:
pruner = optuna.pruners.MedianPruner()
study = optuna.create_study(direction="maximize", pruner=pruner)
study.optimize(objective_logistic, n_trials=10)
print("Mejores hiperparámetros:", study.best_params)

[I 2025-04-18 18:57:34,426] A new study created in memory with name: no-name-d7e8e4fe-0a27-4ba8-8c21-5163ad3cf587
[I 2025-04-18 18:58:26,256] Trial 0 finished with value: 0.4062243077073173 and parameters: {'C': 1.944657234482953e-07, 'penalty': 'l1', 'solver': 'saga'}. Best is trial 0 with value: 0.4062243077073173.
[I 2025-04-18 18:59:09,054] Trial 1 finished with value: 0.2694742170999166 and parameters: {'C': 0.004667536144424552, 'penalty': 'l1', 'solver': 'liblinear'}. Best is trial 0 with value: 0.4062243077073173.
[I 2025-04-18 19:01:59,583] Trial 2 finished with value: 0.4995357581283918 and parameters: {'C': 4.23026460308483, 'penalty': 'l1', 'solver': 'saga'}. Best is trial 2 with value: 0.4995357581283918.
[I 2025-04-18 19:02:54,414] Trial 3 finished with value: 0.5002309604169979 and parameters: {'C': 0.01256637375913343, 'penalty': 'l2', 'solver': 'liblinear'}. Best is trial 3 with value: 0.5002309604169979.
[I 2025-04-18 19:10:27,456] Trial 4 finished with value: 0.4996439733549504 and parameters: {'C': 107090710.38284683, 'penalty': 'l1', 'solver': 'liblinear'}. Best is trial 3 with value: 0.5002309604169979.
[I 2025-04-18 19:11:55,401] Trial 5 finished with value: 0.4977605639843062 and parameters: {'C': 0.008223261143400308, 'penalty': 'l1', 'solver': 'saga'}. Best is trial 3 with value: 0.5002309604169979.
[I 2025-04-18 19:12:37,803] Trial 6 finished with value: 0.3681370449813988 and parameters: {'C': 5.245005207571888e-06, 'penalty': 'l2', 'solver': 'liblinear'}. Best is trial 3 with value: 0.5002309604169979.
[I 2025-04-18 19:14:25,719] Trial 7 finished with value: 0.49962870864848075 and parameters: {'C': 1576087677.6273265, 'penalty': 'l2', 'solver': 'saga'}. Best is trial 3 with value: 0.5002309604169979.
[I 2025-04-18 19:22:13,565] Trial 8 finished with value: 0.4996439733549504 and parameters: {'C': 194622509.18550494, 'penalty': 'l1', 'solver': 'liblinear'}. Best is trial 3 with value: 0.5002309604169979.
[I 2025-04-18 19:23:29,583] Trial 9 finished with value: 0.49945067826814044 and parameters: {'C': 0.388524882554215, 'penalty': 'l1', 'solver': 'liblinear'}. Best is trial 3 with value: 0.5002309604169979.

Mejores hiperparámetros: {'C': 0.01256637375913343, 'penalty': 'l2', 'solver': 'liblinear'}

### Random Forest

In [88]:
def objective_rf(trial):
    n_estimators = trial.suggest_int("n_estimators", 50, 300)
    max_depth = trial.suggest_int("max_depth", 3, 10)
    min_samples_split = trial.suggest_int("min_samples_split", 2, 10)
    min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 5)

    rf_model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        min_samples_leaf=min_samples_leaf,
        random_state=42,
    )

    pipeline_rf = Pipeline(steps=[
            ('preprocessor', preprocessor),
            ('smote', SMOTE(random_state=42)),
            ('model', rf_model)
        ])

    kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
        
    scores = cross_val_score(pipeline_rf, X_train, y_train, cv=kfold, scoring='f1_weighted')
    
    return scores.mean()

In [89]:
pruner = optuna.pruners.MedianPruner()
study = optuna.create_study(direction="maximize", pruner=pruner)
study.optimize(objective_rf, n_trials=10)
print("Best combination:", study.best_params)

[I 2025-04-18 19:44:03,234] A new study created in memory with name: no-name-20762df2-6404-4cd7-b1d3-8bb542c6ef78
[I 2025-04-18 19:45:54,482] Trial 0 finished with value: 0.5244113732323911 and parameters: {'n_estimators': 129, 'max_depth': 3, 'min_samples_split': 7, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.5244113732323911.
[I 2025-04-18 19:49:13,771] Trial 1 finished with value: 0.5095276762368455 and parameters: {'n_estimators': 157, 'max_depth': 6, 'min_samples_split': 9, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.5244113732323911.
[I 2025-04-18 19:51:17,163] Trial 2 finished with value: 0.5155450733391702 and parameters: {'n_estimators': 108, 'max_depth': 5, 'min_samples_split': 2, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.5244113732323911.
[I 2025-04-18 19:55:46,409] Trial 3 finished with value: 0.49898239701371444 and parameters: {'n_estimators': 194, 'max_depth': 7, 'min_samples_split': 10, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.5244113732323911.
[I 2025-04-18 20:03:09,054] Trial 4 finished with value: 0.47585771709421476 and parameters: {'n_estimators': 265, 'max_depth': 9, 'min_samples_split': 2, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.5244113732323911.
[I 2025-04-18 20:10:43,205] Trial 5 finished with value: 0.4685980063595469 and parameters: {'n_estimators': 275, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.5244113732323911.
[I 2025-04-18 20:12:32,652] Trial 6 finished with value: 0.5154618435719229 and parameters: {'n_estimators': 74, 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.5244113732323911.
[I 2025-04-18 20:14:58,704] Trial 7 finished with value: 0.5235829698208461 and parameters: {'n_estimators': 150, 'max_depth': 4, 'min_samples_split': 2, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.5244113732323911.
[I 2025-04-18 20:20:46,821] Trial 8 finished with value: 0.4697286867514007 and parameters: {'n_estimators': 191, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.5244113732323911.
[I 2025-04-18 20:26:19,388] Trial 9 finished with value: 0.47769731103367674 and parameters: {'n_estimators': 245, 'max_depth': 9, 'min_samples_split': 2, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.5244113732323911.

Best combination: {'n_estimators': 129, 'max_depth': 3, 'min_samples_split': 7, 'min_samples_leaf': 4}

### KNN

In [91]:
def objective_knn(trial):
    # Hiperparámetros a optimizar para KNN
    n_neighbors = trial.suggest_int("n_neighbors", 3, 15, step=2)  # Rango impar
    weights = trial.suggest_categorical("weights", ['uniform', 'distance'])
    metric = trial.suggest_categorical("metric", ['euclidean', 'manhattan', 'minkowski'])
    p = trial.suggest_int("p", 1, 2)  # Para la métrica de Minkowski (si es necesario)

    # Crear el modelo KNN
    knn_model = KNeighborsClassifier(
        n_neighbors=n_neighbors,
        weights=weights,
        metric=metric,
        p=p  # Solo si se usa la métrica 'minkowski'
    )
    pipeline_knn = Pipeline(steps=[
            ('preprocessor', preprocessor),
            ('smote', SMOTE(random_state=42)),
            ('model', knn_model)
        ])

    kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
        
    scores = cross_val_score(pipeline_knn, X_train, y_train, cv=kfold, scoring='f1_weighted')
    
    return scores.mean()

In [92]:
pruner = optuna.pruners.MedianPruner()
study = optuna.create_study(direction="maximize", pruner=pruner)
study.optimize(objective_knn, n_trials=10)
print("Best combination:", study.best_params)

[I 2025-04-18 20:27:42,558] A new study created in memory with name: no-name-05f80469-584e-4bd9-865b-ccb9ad1f65aa
[I 2025-04-18 20:28:47,876] Trial 0 finished with value: 0.48453000029651927 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'metric': 'euclidean', 'p': 2}. Best is trial 0 with value: 0.48453000029651927.
[I 2025-04-18 20:32:09,527] Trial 1 finished with value: 0.5191601699148667 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'metric': 'manhattan', 'p': 2}. Best is trial 1 with value: 0.5191601699148667.
[I 2025-04-18 20:35:46,612] Trial 2 finished with value: 0.5209035714852632 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'metric': 'manhattan', 'p': 1}. Best is trial 2 with value: 0.5209035714852632.
[I 2025-04-18 20:37:06,767] Trial 3 finished with value: 0.4736607942840381 and parameters: {'n_neighbors': 11, 'weights': 'uniform', 'metric': 'euclidean', 'p': 2}. Best is trial 2 with value: 0.5209035714852632.
[I 2025-04-18 20:38:21,905] Trial 4 finished with value: 0.49913501833512947 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'metric': 'euclidean', 'p': 2}. Best is trial 2 with value: 0.5209035714852632.
[I 2025-04-18 20:39:27,812] Trial 5 finished with value: 0.4692136293541706 and parameters: {'n_neighbors': 13, 'weights': 'distance', 'metric': 'minkowski', 'p': 2}. Best is trial 2 with value: 0.5209035714852632.
[I 2025-04-18 20:43:50,067] Trial 6 finished with value: 0.5218704832288001 and parameters: {'n_neighbors': 15, 'weights': 'uniform', 'metric': 'minkowski', 'p': 1}. Best is trial 6 with value: 0.5218704832288001.
[I 2025-04-18 20:47:50,796] Trial 7 finished with value: 0.5191743819387475 and parameters: {'n_neighbors': 11, 'weights': 'uniform', 'metric': 'manhattan', 'p': 1}. Best is trial 6 with value: 0.5218704832288001.
[I 2025-04-18 20:52:20,624] Trial 8 finished with value: 0.5212587586954002 and parameters: {'n_neighbors': 13, 'weights': 'distance', 'metric': 'manhattan', 'p': 1}. Best is trial 6 with value: 0.5218704832288001.
[I 2025-04-18 20:53:49,092] Trial 9 finished with value: 0.4736607942840381 and parameters: {'n_neighbors': 11, 'weights': 'uniform', 'metric': 'euclidean', 'p': 2}. Best is trial 6 with value: 0.5218704832288001.

Best combination: {'n_neighbors': 15, 'weights': 'uniform', 'metric': 'minkowski', 'p': 1}

### XGBoost

In [98]:
def objective_xgb(trial):
    learning_rate = trial.suggest_float("learning_rate", 1e-3, 0.3, log=True)
    max_depth = trial.suggest_int("max_depth", 3, 9)
    n_estimators = trial.suggest_int("n_estimators", 50, 300)
    subsample = trial.suggest_float("subsample", 0.6, 1.0)
    gamma = trial.suggest_float("gamma", 0.0, 0.5)


    xgb_model = XGBClassifier(
        learning_rate=learning_rate,
        max_depth=max_depth,
        n_estimators=n_estimators,
        subsample=subsample,
        gamma=gamma,
        random_state=42
    )

    pipeline_xgb = Pipeline(steps=[
            ('preprocessor', preprocessor),
            ('smote', SMOTE(random_state=42)),
            ('model', xgb_model)
        ])

    kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
        
    scores = cross_val_score(pipeline_xgb, X_train, y_train, cv=kfold, scoring='f1_weighted')
    
    return scores.mean()

In [99]:
pruner = optuna.pruners.MedianPruner()
study = optuna.create_study(direction="maximize", pruner=pruner)
study.optimize(objective_xgb, n_trials=10)
print("Best combination:", study.best_params)

[I 2025-04-18 20:54:45,859] A new study created in memory with name: no-name-1b1f03ce-38cb-48be-9171-b6d61694f973
[I 2025-04-18 20:56:41,319] Trial 0 finished with value: 0.5232450857003925 and parameters: {'learning_rate': 0.22473154161955977, 'max_depth': 7, 'n_estimators': 195, 'subsample': 0.6714491914317172, 'gamma': 0.42451530856031827}. Best is trial 0 with value: 0.5232450857003925.
[I 2025-04-18 20:58:28,798] Trial 1 finished with value: 0.5084809924051659 and parameters: {'learning_rate': 0.11084537074304354, 'max_depth': 8, 'n_estimators': 134, 'subsample': 0.6339794966088816, 'gamma': 0.274392542076846}. Best is trial 0 with value: 0.5232450857003925.
[I 2025-04-18 20:59:27,187] Trial 2 finished with value: 0.45077577473613645 and parameters: {'learning_rate': 0.06315776666364713, 'max_depth': 4, 'n_estimators': 86, 'subsample': 0.9501633066989226, 'gamma': 0.4892403346057274}. Best is trial 0 with value: 0.5232450857003925.
[I 2025-04-18 21:00:28,038] Trial 3 finished with value: 0.46997094202114703 and parameters: {'learning_rate': 0.19752906586178987, 'max_depth': 5, 'n_estimators': 90, 'subsample': 0.8139618332168697, 'gamma': 0.044719795570613174}. Best is trial 0 with value: 0.5232450857003925.
[I 2025-04-18 21:01:59,532] Trial 4 finished with value: 0.45105603656641086 and parameters: {'learning_rate': 0.010265337673451431, 'max_depth': 5, 'n_estimators': 234, 'subsample': 0.7834613606531596, 'gamma': 0.35114293065456076}. Best is trial 0 with value: 0.5232450857003925.
[I 2025-04-18 21:03:20,287] Trial 5 finished with value: 0.4598766494010957 and parameters: {'learning_rate': 0.001548034658063368, 'max_depth': 7, 'n_estimators': 118, 'subsample': 0.9018312472746305, 'gamma': 0.363544006860295}. Best is trial 0 with value: 0.5232450857003925.
[I 2025-04-18 21:04:59,415] Trial 6 finished with value: 0.5176064597724239 and parameters: {'learning_rate': 0.2326951178958088, 'max_depth': 7, 'n_estimators': 153, 'subsample': 0.9483168633008059, 'gamma': 0.395576247436131}. Best is trial 0 with value: 0.5232450857003925.
[I 2025-04-18 21:06:06,107] Trial 7 finished with value: 0.47709104447924017 and parameters: {'learning_rate': 0.1346773717154836, 'max_depth': 7, 'n_estimators': 63, 'subsample': 0.6898620644161538, 'gamma': 0.40845420293649803}. Best is trial 0 with value: 0.5232450857003925.
[I 2025-04-18 21:06:59,363] Trial 8 finished with value: 0.46444476522092265 and parameters: {'learning_rate': 0.012508568984568563, 'max_depth': 3, 'n_estimators': 116, 'subsample': 0.9532643723349974, 'gamma': 0.1337687431377862}. Best is trial 0 with value: 0.5232450857003925.
[I 2025-04-18 21:09:29,420] Trial 9 finished with value: 0.4509441409194757 and parameters: {'learning_rate': 0.007009581275262688, 'max_depth': 8, 'n_estimators': 256, 'subsample': 0.8982010775697227, 'gamma': 0.048400092158251584}. Best is trial 0 with value: 0.5232450857003925.

Best combination: {'learning_rate': 0.22473154161955977, 'max_depth': 7, 'n_estimators': 195, 'subsample': 0.6714491914317172, 'gamma': 0.42451530856031827}

### Neural Networks

In [49]:
def objective_nn(trial):
    # Hiperparámetros a optimizar para la red neuronal
    hidden_layer_sizes = trial.suggest_categorical("hidden_layer_sizes", [(100,), (100, 50), (50, 50)])
    activation = trial.suggest_categorical("activation", ["relu", "tanh", "logistic"])
    solver = trial.suggest_categorical("solver", ["adam", "sgd"])
    alpha = trial.suggest_float("alpha", 1e-5, 1e-1, log=True)
    learning_rate_init = trial.suggest_float("learning_rate_init", 1e-5, 1e-1, log=True)

    # Crear el modelo de red neuronal
    nn_model = MLPClassifier(
        hidden_layer_sizes=hidden_layer_sizes,
        activation=activation,
        solver=solver,
        alpha=alpha,
        learning_rate_init=learning_rate_init,
        max_iter=1000,  # Ajusta según sea necesario
        random_state=42,
    )

    # Define el pipeline con tu preprocesador (preprocessor)
    pipeline_nn = Pipeline(steps=[('preprocessor', preprocessor), ('model', nn_model)])

    # Ajusta el pipeline a tus datos de entrenamiento
    pipeline_nn.fit(X_train, y_train)

    # Realiza predicciones en el conjunto de prueba
    y_pred_nn = pipeline_nn.predict(X_test)

    # Calcula el F1-score y devuélvelo
    f1 = f1_score(y_test, y_pred_nn)
    return f1

In [50]:
# Crea el estudio con el MedianPruner
study = optuna.create_study(
    direction="maximize",
    pruner=optuna.pruners.MedianPruner(
        n_startup_trials=5,  # Número de ensayos iniciales sin pruning
        n_warmup_steps=10,   # Número de pasos antes de empezar a evaluar el pruning
        interval_steps=1,     # Frecuencia de evaluación del pruning
    ),
)

# Optimiza la función objetivo
study.optimize(objective_nn, n_trials=10)  # Ajusta el número de ensayos según sea necesario

# Imprime los mejores hiperparámetros encontrados
print("Mejores hiperparámetros:", study.best_params)

[I 2025-04-18 16:05:59,651] A new study created in memory with name: no-name-c6c433e3-cbc6-4f22-89d5-ef635100d59d
[I 2025-04-18 16:13:42,330] Trial 0 finished with value: 0.6423820730584263 and parameters: {'hidden_layer_sizes': (100, 50), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.00017639076074801822, 'learning_rate_init': 0.011241004618312928}. Best is trial 0 with value: 0.6423820730584263.
[I 2025-04-18 16:14:41,256] Trial 1 finished with value: 0.6876959619952494 and parameters: {'hidden_layer_sizes': (100, 50), 'activation': 'relu', 'solver': 'adam', 'alpha': 5.0504647986667555e-05, 'learning_rate_init': 0.0003917581328874582}. Best is trial 1 with value: 0.6876959619952494.
[I 2025-04-18 16:14:44,516] Trial 2 finished with value: 0.6512102951690328 and parameters: {'hidden_layer_sizes': (50, 50), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 1.6757701746487853e-05, 'learning_rate_init': 4.070488847274107e-05}. Best is trial 1 with value: 0.6876959619952494.
[I 2025-04-18 16:15:10,264] Trial 3 finished with value: 0.693954541167594 and parameters: {'hidden_layer_sizes': (100, 50), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.01261555694120768, 'learning_rate_init': 0.001887483508805306}. Best is trial 3 with value: 0.693954541167594.
[I 2025-04-18 16:15:21,570] Trial 4 finished with value: 0.7468663245562379 and parameters: {'hidden_layer_sizes': (100, 50), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00019324521336064806, 'learning_rate_init': 0.000649258805024746}. Best is trial 4 with value: 0.7468663245562379.
[I 2025-04-18 16:15:30,681] Trial 5 finished with value: 0.7504787278328199 and parameters: {'hidden_layer_sizes': (100,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0013353412373902245, 'learning_rate_init': 0.0005098823513914143}. Best is trial 5 with value: 0.7504787278328199.
[I 2025-04-18 16:15:47,487] Trial 6 finished with value: 0.7479906229068989 and parameters: {'hidden_layer_sizes': (100, 50), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.00034033616276690103, 'learning_rate_init': 8.363882558421207e-05}. Best is trial 5 with value: 0.7504787278328199.
[W 2025-04-18 16:16:05,357] Trial 7 failed with parameters: {'hidden_layer_sizes': (50, 50), 'activation': 'logistic', 'solver': 'adam', 'alpha': 0.026896289945509032, 'learning_rate_init': 0.03179170511913835} because of the following error: KeyboardInterrupt().
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "<ipython-input-49-a26ff60bfc4e>", line 27, in objective_nn
    y_pred_nn = pipeline_nn.predict(X_test)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/pipeline.py", line 787, in predict
    Xt = transform.transform(Xt)
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/utils/_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/compose/_column_transformer.py", line 1101, in transform
    Xs = self._call_func_on_transformers(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/compose/_column_transformer.py", line 910, in _call_func_on_transformers
    return Parallel(n_jobs=self.n_jobs)(jobs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/utils/parallel.py", line 77, in __call__
    return super().__call__(iterable_with_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/joblib/parallel.py", line 1918, in __call__
    return output if self.return_generator else list(output)
                                                ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/joblib/parallel.py", line 1847, in _get_sequential_output
    res = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/utils/parallel.py", line 139, in __call__
    return self.function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/pipeline.py", line 1531, in _transform_one
    res = transformer.transform(X, **params.transform)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/pipeline.py", line 1092, in transform
    Xt = transform.transform(Xt, **routed_params[name].transform)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/utils/_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/preprocessing/_encoders.py", line 1043, in transform
    X_int, X_mask = self._transform(
                    ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/preprocessing/_encoders.py", line 212, in _transform
    if not np.all(valid_mask):
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/numpy/_core/fromnumeric.py", line 2601, in all
    return _wrapreduction_any_all(a, np.logical_and, 'all', axis, out,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/numpy/_core/fromnumeric.py", line 102, in _wrapreduction_any_all
    return ufunc.reduce(obj, axis, bool, out, **passkwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
[W 2025-04-18 16:16:05,365] Trial 7 failed with value None.

KeyboardInterrupt:

## TEST WITH BEST PARAMETERS

In [25]:
from sklearn.metrics import classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score
from sklearn.neighbors import KNeighborsClassifier
from xgboost import XGBClassifier
from sklearn.neural_network import MLPClassifier

### RANDOM FOREST

In [101]:
pipeline_rf = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('smote', SMOTE(random_state=42)),
    ('model', RandomForestClassifier(n_estimators=129, max_depth=3, min_samples_split=7, min_samples_leaf=4, random_state=42))
])

pipeline_rf.fit(X_train, y_train)

y_pred_test = pipeline_rf.predict(X_test)
y_pred_train = pipeline_rf.predict(X_train)

print(classification_report(y_test, y_pred_test))

print(classification_report(y_train, y_pred_train))

              precision    recall  f1-score   support

           0       0.40      0.35      0.37      5993
           1       0.60      0.65      0.63      9014

    accuracy                           0.53     15007
   macro avg       0.50      0.50      0.50     15007
weighted avg       0.52      0.53      0.53     15007

              precision    recall  f1-score   support

           0       0.41      0.36      0.39     23973
           1       0.61      0.66      0.63     36055

    accuracy                           0.54     60028
   macro avg       0.51      0.51      0.51     60028
weighted avg       0.53      0.54      0.54     60028

### LOGISTIC REGRESSION

In [50]:
# Crear el modelo con los mejores hiperparámetros
best_logistic_model = LogisticRegression(
    #C=0.01256637375913343,
    C=10,
    penalty='l2',
    #solver='liblinear',
    solver='saga',
    max_iter=100000, # Asegurar la convergencia
    random_state=42  # Reproducibilidad
)

# Crear el pipeline con el preprocesador y el modelo
pipeline_logistic = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('smote', SMOTE(random_state=42)),
    ('model', best_logistic_model)
])

# Entrenar el pipeline con los datos de entrenamiento
pipeline_logistic.fit(X_train, y_train)

# Realizar las predicciones sobre el test de prueba
y_pred_test = pipeline_logistic.predict(X_test)
y_pred_train = pipeline_logistic.predict(X_train)

# Imprimir el classification report
print(classification_report(y_test, y_pred_test))

print(classification_report(y_train, y_pred_train))

              precision    recall  f1-score   support

           0       0.40      0.52      0.45      2997
           1       0.60      0.47      0.53      4507

    accuracy                           0.49      7504
   macro avg       0.50      0.50      0.49      7504
weighted avg       0.52      0.49      0.50      7504

              precision    recall  f1-score   support

           0       0.40      0.54      0.46     26969
           1       0.61      0.47      0.53     40562

    accuracy                           0.50     67531
   macro avg       0.51      0.51      0.50     67531
weighted avg       0.53      0.50      0.50     67531

### KNN

In [102]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report

# Crear el modelo con los mejores hiperparámetros
best_knn_model = KNeighborsClassifier(
    n_neighbors=15,
    weights='uniform',
    metric='minkowski',
    p=1 
)

# Crear el pipeline con el preprocesador y el modelo
pipeline_knn = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('smote', SMOTE(random_state=42)),
    ('model', best_knn_model)
])

# Entrenar el pipeline con los datos de entrenamiento
pipeline_knn.fit(X_train, y_train)

# Realizar las predicciones sobre el test de prueba
y_pred_test = pipeline_knn.predict(X_test)
y_pred_train = pipeline_knn.predict(X_train)

# Imprimir el classification report
print(classification_report(y_test, y_pred_test))
print(classification_report(y_train, y_pred_train))

              precision    recall  f1-score   support

           0       0.41      0.40      0.40      5993
           1       0.61      0.61      0.61      9014

    accuracy                           0.53     15007
   macro avg       0.51      0.51      0.51     15007
weighted avg       0.53      0.53      0.53     15007

              precision    recall  f1-score   support

           0       0.55      0.57      0.56     23973
           1       0.71      0.69      0.70     36055

    accuracy                           0.64     60028
   macro avg       0.63      0.63      0.63     60028
weighted avg       0.65      0.64      0.65     60028

### XGBoost

In [110]:
# Crear el modelo con los mejores hiperparámetros
best_xgb_model = XGBClassifier(
    scale_pos_weight = len(y_train[y_train == 0]) / len(y_train[y_train == 1]),
    learning_rate=0.22473154161955977,
    max_depth=3,
    n_estimators=195,
    subsample=0.6714491914317172,
    gamma=0.42451530856031827,
    random_state=42  # Para reproducibilidad
)


# Crear el pipeline con el preprocesador y el modelo
pipeline_xgb = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('smote', SMOTE(random_state=42)),
    ('model', best_xgb_model)
])

# Entrenar el pipeline con los datos de entrenamiento
pipeline_xgb.fit(X_train, y_train)

# Realizar las predicciones sobre el test de prueba
y_pred_test = pipeline_xgb.predict(X_test)
y_pred_train = pipeline_xgb.predict(X_train)

# Imprimir el classification report
print(classification_report(y_test, y_pred_test))
print(classification_report(y_train, y_pred_train))

              precision    recall  f1-score   support

           0       0.40      0.55      0.46      5993
           1       0.60      0.46      0.52      9014

    accuracy                           0.49     15007
   macro avg       0.50      0.50      0.49     15007
weighted avg       0.52      0.49      0.50     15007

              precision    recall  f1-score   support

           0       0.46      0.62      0.53     23973
           1       0.67      0.51      0.58     36055

    accuracy                           0.56     60028
   macro avg       0.57      0.57      0.56     60028
weighted avg       0.59      0.56      0.56     60028

In [163]:
patient_test_data = pd.read_csv('g:/Mi unidad/PROYECTOS/DM_II_project/data/raw/patient_test_data.csv')

In [164]:
patient_test_data.shape

(75000, 31)

In [165]:
patient_test_data_reduced = patient_test_data.drop(columns=['Diabetes History', 'Marital Status', 'Transfusion History'], axis=1).copy()

In [166]:
patient_test_data.shape

(75000, 31)

In [167]:
continents = {
    'USA': 'North America',
    'Brazil': 'South America',
    'Germany': 'Europe',
    'France': 'Europe',
    'Italy': 'Europe',
    'UK': 'Europe',
    'China': 'Asia',
    'Japan': 'Asia',
    'India': 'Asia',
    'South Korea': 'Asia',
    'Pakistan': 'Asia',
    'South Africa': 'Africa',
    'Nigeria': 'Africa',
    'Australia': 'Oceania',
    'New Zealand': 'Oceania'
}
patient_test_data_reduced['Continent'] = patient_test_data_reduced['Country'].replace(continents)
patient_test_data_reduced.drop(columns=['Country'], inplace=True)
patient_test_data_reduced['Continent'].head()

0           Europe
1    North America
2           Europe
3             Asia
4             Asia
Name: Continent, dtype: object

In [168]:
patient_test_data.shape

(75000, 31)

In [169]:
patient_test_data_reduced['Date of Birth'] = pd.to_datetime(patient_test_data_reduced['Date of Birth'], format='%d-%m-%Y', errors='coerce')
patient_test_data_reduced['Age'] = patient_test_data_reduced['Date of Birth'].apply(lambda x: datetime.now().year - x.year if pd.notnull(x) else None)
patient_test_data_reduced.drop(columns=['Date of Birth'], inplace=True)
patient_test_data_reduced['Age'].head()

0    78.0
1    83.0
2    89.0
3    54.0
4    53.0
Name: Age, dtype: float64

In [171]:
patient_test_data_reduced.shape

(75000, 28)

In [172]:
patient_test_data_reduced['Urban or Rural'].replace({'urban': 'Urban', 'rural': 'Rural'}, inplace=True)

In [173]:
patient_test_data_reduced.drop(columns=['ID'], axis=1, inplace=True)

In [174]:
patient_test_data_reduced.shape

(75000, 27)

In [175]:
patient_test_data_reduced.shape

(75000, 27)

In [176]:
pipeline_xgb.fit(X_train, y_train)
y_pred_kaggle = pipeline_xgb.predict(patient_test_data_reduced)

In [177]:
y_pred_kaggle.shape

(75000,)

In [186]:
predictions_with_id = pd.DataFrame({
    'ID': patient_test_data['ID'],
    'Survival Prediction': y_pred_kaggle
}, index=None)

predictions_with_id['Survival Prediction'].replace({0: 'No', 1: 'Yes'}, inplace=True)
predictions_with_id.head()

      ID Survival Prediction
0  75036                 Yes
1  75037                  No
2  75038                 Yes
3  75039                 Yes
4  75040                 Yes

In [191]:
predictions_with_id.to_csv('g:/Mi unidad/PROYECTOS/DM_II_project/data/predictions.csv', index=False, header=True)